name: Build Resume PDF

on:
  push:
    paths:
      - resume_eunlim.md
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-xetex texlive-fonts-recommended fonts-noto fonts-noto-cjk

      - name: Convert Markdown to PDF
        run: |
          pandoc resume_eunlim.md -o resume_eunlim.pdf --pdf-engine=xelatex

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Resume PDF
          path: resume_eunlim.pdf
